language: rust
rust: [stable, beta, nightly]
cache: cargo

install:
  - "export RUSTFLAGS=$(cargo --version | grep nightly >/dev/null && echo \"-Z external-macro-backtrace\")"
  - "rustup component add rustfmt --toolchain $(rustup show active-toolchain | cut -d\" \" -f1)"
  - cargo install just wasm-pack

script:
  - just npm dist
  - cargo test --all
  - cargo fmt --all -- --check
